-- Init role
INSERT INTO ROLE (ID, VERSION, NAME, DESCRIPTION) VALUES (1, 0, 'ROLE_ADMIN', 'Admin');
INSERT INTO ROLE (ID, VERSION, NAME, DESCRIPTION) VALUES (2, 0, 'ROLE_MANAGER', 'Manager');
INSERT INTO ROLE (ID, VERSION, NAME, DESCRIPTION) VALUES (3, 0, 'ROLE_CASHIER', 'Cashier');
INSERT INTO ROLE (ID, VERSION, NAME, DESCRIPTION) VALUES (4, 0, 'ROLE_STYLIST', 'Stylist');
INSERT INTO ROLE (ID, VERSION, NAME, DESCRIPTION) VALUES (5, 0, 'ROLE_CUSTOMER', 'Customer');
--  Update admin account password encrypted (plaintext: admin)
INSERT INTO ACCOUNT (ID, USERNAME, PASSWORD, VERSION)
VALUES (1, 'admin', '$2a$10$xRB6mR5oBfzo46LIx6I6lueNg53Voq07.jpale6VfTxaMK/HLPyDO', 0);
-- Add admin role
INSERT INTO ACCOUNT_ROLE (ACCOUNT_ID, ROLE_ID) VALUES (1,1);